env:
  node: true
plugins:
  - node
  - standard
  - promise
  - flowtype
extends:
  - eslint:recommended
  - plugin:node/recommended
rules:
  node/no-unsupported-features: [error, {version: 4}]
  no-console: 0
